version: 2.1

# CircleCI doesn't handle large file sets properly for local builds
# https://github.com/CircleCI-Public/circleci-cli/issues/281#issuecomment-472808051
localCheckout: &localCheckout
  run: |-
    PROJECT_PATH=$(cd ${CIRCLE_WORKING_DIRECTORY}; pwd)
    mkdir -p ${PROJECT_PATH}
    cd /tmp/_circleci_local_build_repo
    git ls-files -z | xargs -0 -s 2090860 tar -c | tar -x -C ${PROJECT_PATH}
    cp -a /tmp/_circleci_local_build_repo/.git ${PROJECT_PATH}

jobs:
  ubuntu_build:
    description: A template for running liboqs-dotnet tests on x64 Ubuntu Focal Docker VMs
    docker:
      - image: openquantumsafe/ci-ubuntu-focal-x86_64:latest
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
      - checkout # change this from "checkout" to "*localCheckout" when running CircleCI locally
      - run:
          name: Install pre-requisites
          command: |
            git clone --branch main --single-branch --depth 1 https://github.com/open-quantum-safe/liboqs.git
            cd /root && wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && dpkg -i packages-microsoft-prod.deb && apt-get update && apt-get install -y apt-transport-https && apt-get update && apt-get install -y dotnet-sdk-3.1 && cd -
      - run:
          name: Clone liboqs
          command: .circleci/clone_liboqs.sh
      - run:
          name: Build liboqs
          command: .circleci/build_liboqs.sh
      - run:
          name: Build wrapper
          command: dotnet build dotnetOQS/dotnetOQS.csproj /p:Platform=AnyCPU -f netstandard1.2 -c Release -o bin/Release/dotnetOQS-netstandard1.2
      - run:
          name: Build and run test app
          command: scripts/linux_sample_netcoreapp2.1_x64_build.sh && ./bin/Release/dotnetOQSSample-netcoreapp2.1-linux-x64/dotnetOQSSample

  macOS:
    description: A template for running liboqs-dotnet tests on x64 macOS machines
    macos:
      xcode: "13.2.1"
    steps:
      - checkout # change this from "checkout" to "*localCheckout" when running CircleCI locally
      - run:
          name: Install dependencies
          command: |
            env HOMEBREW_NO_AUTO_UPDATE=1 brew install cmake ninja mono-libgdiplus
            curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel LTS > dotnetinstall.log ; cat dotnetinstall.log
      - run:
          name: Clone liboqs
          command: .circleci/clone_liboqs.sh
      - run:
          name: Build and install liboqs
          command: .circleci/build_liboqs.sh
      - run:
          name: Build wrapper
          command: export PATH=~/.dotnet:$PATH && dotnet build dotnetOQS/dotnetOQS.csproj /p:Platform=AnyCPU -f netstandard1.2 -c Release -o bin/Release/dotnetOQS-netstandard1.2
      - run:
          name: Build and run test app
          command: export PATH=~/.dotnet:$PATH && scripts/macos_sample_netcoreapp2.1_x64_build.sh && ./bin/Release/dotnetOQSSample-netcoreapp2.1-osx-x64/dotnetOQSSample

workflows:
  version: 2.1
  build:
    jobs:
      - ubuntu_build:
          name: ubuntu
      - macOS:
          name: mac
